CREATE STREAM ERROR_STREAM
(
    CODE INTEGER
)
WITH (
    KAFKA_TOPIC = '',
    VALUE_FORMAT = 'JSON'
);


CREATE STREAM window404_topic 
WITH (
    KAFKA_TOPIC = '',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    CODE, COUNT(*)
FROM ERROR_STREAM
WHERE CODE=404
WINDOW TUMBLING (SIZE 60 SECONDS)
GROUP BY CODE EMIT CHANGES;


CREATE STREAM window405_topic 
WITH (
    KAFKA_TOPIC = '',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    CODE, COUNT(*)
FROM ERROR_STREAM
WHERE CODE=405
WINDOW TUMBLING (SIZE 60 SECONDS)
GROUP BY CODE EMIT CHANGES;


CREATE STREAM window406_topic 
WITH (
    KAFKA_TOPIC = '',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    CODE, COUNT(*)
FROM ERROR_STREAM
WHERE CODE=406
WINDOW TUMBLING (SIZE 60 SECONDS)
GROUP BY CODE EMIT CHANGES;


CREATE STREAM window407_topic 
WITH (
    KAFKA_TOPIC = '',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    CODE, COUNT(*)
FROM ERROR_STREAM
WHERE CODE=407
WINDOW TUMBLING (SIZE 60 SECONDS)
GROUP BY CODE EMIT CHANGES;