CREATE STREAM error_count
(
    CODE INTEGER,
    COUNT_VALUE INTEGER
)
WITH (
    KAFKA_TOPIC = 'error_count',
    VALUE_FORMAT = 'JSON'
); 

CREATE STREAM 404_count
WITH (
    KAFKA_TOPIC = '404_count',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    ROWTIME as time,
    CODE,
    COUNT_VALUE
FROM error_count
WHERE CODE=404
PARTITION BY CODE; 

CREATE STREAM 405_count
WITH (
    KAFKA_TOPIC = '405_count',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    ROWTIME as time,
    CODE,
    COUNT_VALUE
FROM error_count
WHERE CODE=405
PARTITION BY CODE; 

CREATE STREAM 406_count
WITH (
    KAFKA_TOPIC = '406_count',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    ROWTIME as time,
    CODE,
    COUNT_VALUE
FROM error_count
WHERE CODE=406
PARTITION BY CODE; 

CREATE STREAM 407_count
WITH (
    KAFKA_TOPIC = '407_count',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    ROWTIME as time,
    CODE,
    COUNT_VALUE
FROM error_count
WHERE CODE=407
PARTITION BY CODE; 
