# create the stream ERROR_STREAM from the preexisting kafka topic ERROR LOG
CREATE STREAM ERROR_STREAM
(
    CODE INTEGER
)
WITH (
    KAFKA_TOPIC = 'ERROR_LOG',
    VALUE_FORMAT = 'JSON'
);

# create table WINDOW_404 from preexisting kafka topic 404_ERRORS
CREATE TABLE WINDOW_404 
WITH (
    KAFKA_TOPIC = '404_ERRORS',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    CODE, COUNT(*) AS ERROR_404_COUNT
FROM ERROR_STREAM 
WHERE CODE=404
GROUP BY CODE EMIT CHANGES;
# WINDOW TUMBLING (SIZE 60 SECONDS)
# create table WINDOW_405 from preexisting kafka topic 404_ERRORS
CREATE TABLE WINDOW_405
WITH (
    KAFKA_TOPIC = '405_ERRORS',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
   CODE, COUNT(*) AS ERROR_405_COUNT
FROM ERROR_STREAM WINDOW TUMBLING (SIZE 60 SECONDS)
WHERE CODE=405
GROUP BY CODE EMIT CHANGES;

# create table WINDOW_406 from preexisting kafka topic 404_ERRORS
CREATE TABLE WINDOW_406 
WITH (
    KAFKA_TOPIC = '406_ERRORS',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
   CODE, COUNT(*) AS ERROR_406_COUNT
FROM ERROR_STREAM WINDOW TUMBLING (SIZE 60 SECONDS)
WHERE CODE=406
GROUP BY CODE EMIT CHANGES;

# create table WINDOW_407 from preexisting kafka topic 404_ERRORS
CREATE TABLE WINDOW_407 
WITH (
    KAFKA_TOPIC = '407_ERRORS',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
   CODE, COUNT(*) AS ERROR_407_COUNT
FROM ERROR_STREAM WINDOW TUMBLING (SIZE 60 SECONDS)
WHERE CODE=407
GROUP BY CODE EMIT CHANGES;