CREATE STREAM ERROR_LOG
(
    CODE INTEGER
)
WITH (
    KAFKA_TOPIC = 'ERROR_LOG',
    VALUE_FORMAT = 'JSON'
);

# create table WINDOW_404 from preexisting kafka topic 404_ERRORS 
#subquery to get 404 error count from 404 topic over last 60 seconds 

CREATE TABLE 404_ERROR_COUNT
WITH (
    KAFKA_TOPIC = '404_ERROR_COUNT',
    VALUE_FORMAT = 'JSON'
) AS
SELECT 
    COUNT(*) AS ERROR_404_COUNT
FROM ERROR_LOG WINDOW HOPPING (SIZE 60 SECONDS, ADVANCE BY 5 SECONDS)
WHERE CODE=404
GROUP BY CODE EMIT CHANGES;

# create table WINDOW_405 from preexisting kafka topic 405_ERRORS 

CREATE TABLE 405_ERROR_COUNT
WITH (
    KAFKA_TOPIC = '405_ERROR_COUNT',
    VALUE_FORMAT = 'JSON'
) AS

#subquery to get 405 error count from 405 topic over last 60 seconds 

SELECT 
    COUNT(*) AS ERROR_405_COUNT
FROM ERROR_LOG WINDOW HOPPING (SIZE 60 SECONDS, ADVANCE BY 5 SECONDS)
WHERE CODE=405
GROUP BY CODE EMIT CHANGES;

# create table WINDOW_406 from preexisting kafka topic 406_ERRORS 

CREATE TABLE ERROR_406_COUNT
WITH (
    KAFKA_TOPIC = '406_ERROR_COUNT',
    VALUE_FORMAT = 'JSON'
) AS

#subquery to get 406 error count from 406 topic over last 60 seconds 

SELECT 
    COUNT(*) AS ERROR_406_COUNT
FROM ERROR_LOG WINDOW HOPPING (SIZE 60 SECONDS, ADVANCE BY 5 SECONDS)
WHERE CODE=406
GROUP BY CODE EMIT CHANGES;

# create table WINDOW_407 from preexisting kafka topic 407_ERRORS 

CREATE TABLE 407_ERROR_COUNT
WITH (
    KAFKA_TOPIC = '407_ERROR_COUNT',
    VALUE_FORMAT = 'JSON'
) AS

#subquery to get 407 error count from 407 topic over last 60 seconds 

SELECT 
    COUNT(*) AS ERROR_407_COUNT
FROM ERROR_LOG WINDOW HOPPING (SIZE 60 SECONDS, ADVANCE BY 5 SECONDS)
WHERE CODE=407
GROUP BY CODE EMIT CHANGES;